import React from 'react';
import { StyleProp, TextStyle } from 'react-native';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';

export type IconName =
  | 'menu'
  | 'notifications'
  | 'shopping-cart'
  | 'home'
  | 'storefront'
  | 'shopping-basket'
  | 'person'
  | 'search'
  | 'local-shipping'
  | 'verified-user'
  | 'support-agent'
  | 'replay'
  | 'computer'
  | 'checkroom'
  | 'construction'
  | 'agriculture'
  | 'business-center'
  | 'auto-awesome'
  | 'add-shopping-cart'
  | 'mail'
  | 'chevron-right'
  | 'star'
  | 'star-border'
  | 'favorite'
  | 'favorite-border'
  | 'tune'
  | 'bolt'
  | 'verified'
  | 'inventory'
  | 'check-circle'
  | 'launch'
  | 'location-on'
  | 'call'
  | 'share'
  | 'memory'
  | 'photo-camera'
  | 'battery-charging-full'
  | 'sd-card'
  | 'chat'
  | 'chat-bubble'
  | 'help'
  | 'trending-up'
  | 'filter-list'
  | 'sync'
  | 'public'
  | 'shopping-bag'
  | 'store'
  | 'arrow-forward'
  | 'star-half'
  | 'qr-code'
  | 'alternate-email'
  | 'close'
  | 'keyboard-arrow-down'
  | 'fast-forward'
  | 'remove'
  | 'add'
  | 'check'
  | 'delete-outline'
  | 'login'
  | 'logout'
  | 'lock'
  | 'email'
  | 'visibility'
  | 'visibility-off'
  | 'person-add'
  | 'person-outline'
  | 'exit-to-app'
  | 'receipt-long'
  | 'history'
  | 'settings'
  | 'info'
  | 'account-circle'
  | 'keyboard-arrow-up'
  | 'list'
  | 'sell'
  | 'payment'
  | 'description'
  | 'credit-card'
  | 'account-balance-wallet'
  | 'currency-bitcoin'
  | 'local-atm'
  | 'smartphone'
  | 'error-outline'
  | 'people'
  | 'lightbulb'
  | 'eco'
  | 'track-changes'
  | 'build'
  | 'groups'
  | 'handshake'
  | 'gavel'
  | 'radio-button-unchecked'
  | 'radio-button-checked'
  | 'check-box'
  | 'check-box-outline-blank'
  | 'edit'
  | 'edit-note'
  | 'help-outline'
  | 'more-horiz'
  | 'flag'
  | 'my-location'
  | 'schedule'
  | 'place'
  | 'map'
  | 'event'
  | 'directions-car'
  | 'restaurant'
  | 'palette'
  | 'send'

interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  style?: StyleProp<TextStyle>;
}

export function Icon({ name, size = 24, color, style }: IconProps) {
  return <MaterialIcons name={name} size={size} color={color} style={style} />;
}
